services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_RESTRICT_FILE_ACCESS_TO=/files;/home/node/.n8n-files
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Asia/Dhaka
      - TZ=Asia/Dhaka
    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files
    depends_on:
      - voterdb
      - ocr

  ocr:
    build: ./ocr
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/output

  voterdb:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npassword
      POSTGRES_DB: voter_data
    ports:
      - "5432:5432"
    volumes:
      - voterdb_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  voterdb_data: